### ISSUE TITLE
[Bug] Completion text is inserted when ncm2-ultisnips is installed

### ISSUE THREAD

**Issue by bolstycjw** [ncm2/ncm2-ultisnips#4] opened 2018-07-21 16:18 UTC
![out](https://user-images.githubusercontent.com/11256605/43037789-9112ad34-8d44-11e8-9f48-c7447bbc3b3d.gif)

This happens when completion item does not include a snippet. 

Completion works fine when ncm-ultisnips is not installed.

# Plugins installed
Plug 'SirVer/ultisnips'
Plug 'ncm2/ncm2-ultisnips'
Plug 'ncm2/ncm2'
Plug 'roxma/nvim-yarp'
Plug 'autozimu/LanguageClient-neovim',    { 'branch': 'next', 'do': 'bash install.sh' }

**Comment by roxma** [comment] 2018-07-22 03:04
Your vimrc is incomplete. I cannot reproduce.

**Comment by bolstycjw** [comment] 2018-07-22 03:48
Sorry about that. Please try the minimal vimrc below

# Minimal vimrc
```
call plug#begin('~/.local/share/nvim/plugged')

Plug 'SirVer/ultisnips'
Plug 'ncm2/ncm2-ultisnips'
Plug 'ncm2/ncm2'
Plug 'roxma/nvim-yarp'
Plug 'autozimu/LanguageClient-neovim',    { 'branch': 'next', 'do': 'bash install.sh' }
call plug#end()

set hidden

let g:ncm2#complete_length = [[1,4],[7,2]]

let g:LanguageClient_serverCommands = {
      \ 'cpp': ['cquery', '--log-file=/tmp/cq.log', '--init={"cacheDirectory":"/tmp/cquery/cache"}'],
      \ 'c': ['cquery', '--log-file=/tmp/cq.log', '--init={"cacheDirectory":"/tmp/cquery/cache"}'],
      \ }

autocmd BufEnter * call ncm2#enable_for_buffer()
set completeopt=noinsert,menuone,noselect
set shortmess+=c

au TextChangedI * call ncm2#auto_trigger()
```

**Comment by roxma** [comment] 2018-07-22 15:54
There is bug-fix when I test this vimrc with cquery.

But I cannot reproduce the issue you have. Please use the latest version.

**Comment by roxma** [comment] 2018-07-22 16:08
![peek 2018-07-23 00-06](https://user-images.githubusercontent.com/4538941/43047604-701063b0-8e0c-11e8-83fb-90aac36cef55.gif)


Closing. Cannot reproduce.

**Comment by roxma** [comment] 2018-07-22 16:14
You should probably report an issue to cquery, since it sends a wrong `textEdit` (the line number in the demo is wrong) to the client sometimes.

![peek 2018-07-23 00-09](https://user-images.githubusercontent.com/4538941/43047667-4b9f5936-8e0d-11e8-9ea0-ba7f865576be.gif)

**Comment by languitar** [comment] 2018-07-23 15:30
I am experiencing the same issue with python completion. As soon as this plugin is used, all completions from the language server behave as in the initial gif, even if they are not expandable by ultisnips.

**Comment by languitar** [comment] 2018-07-23 15:46
Just for completeness, here is my vimrc and screencast:

```viml
set nocompatible

filetype off

call plug#begin('~/.local/share/nvim/bundle/')
Plug 'SirVer/ultisnips'
Plug 'ncm2/ncm2'
Plug 'roxma/nvim-yarp'
Plug 'ncm2/ncm2-bufword'
Plug 'ncm2/ncm2-ultisnips'
Plug 'autozimu/LanguageClient-neovim', {'branch': 'next', 'do': 'make release'}
call plug#end()

let g:LanguageClient_serverCommands = {
    \ 'python': ['pyls'],
    \ }
let g:LanguageClient_autoStart = 1

augroup vimrc
    autocmd!
augroup END

set hidden

autocmd vimrc BufEnter * call ncm2#enable_for_buffer()
set completeopt=noinsert,menuone,preview,noselect
set shortmess+=c
let g:ncm2#comple_length=1
```

![cast](https://user-images.githubusercontent.com/1336287/43087498-50c1091c-8ea0-11e8-9953-75e5737b0a57.gif)

**Closed as completed** 2018-07-24 01:09 UTC
Labels: cannot-reproduce

**Comment by languitar** [comment] 2018-07-24 09:56
thanks
